version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-batumi_lunch}
      POSTGRES_USER: ${POSTGRES_USER:-batumi}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-batumi_pass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-batumi}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-batumi_secret}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.api
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "8000:8000"

  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.web
    env_file:
      - ../.env
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  minio_data:
