services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: batumi_lunch
      POSTGRES_USER: batumi_lunch
      POSTGRES_PASSWORD: batumi_lunch
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address :9090
    environment:
      MINIO_ROOT_USER: local-key
      MINIO_ROOT_PASSWORD: local-secret
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data

  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.api
    env_file:
      - ../.env.sample
    environment:
      BATUMI_LUNCH_DATABASE_URL: postgresql+psycopg://batumi_lunch:batumi_lunch@postgres:5432/batumi_lunch
      BATUMI_LUNCH_REDIS_URL: redis://redis:6379/0
      BATUMI_LUNCH_S3_ENDPOINT_URL: http://minio:9000
      BATUMI_LUNCH_S3_ACCESS_KEY: local-key
      BATUMI_LUNCH_S3_SECRET_KEY: local-secret
      BATUMI_LUNCH_S3_BUCKET: batumi-lunch-media
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "8000:8000"

  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.web
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  minio_data:
