FROM node:20-alpine AS base

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json* ./frontend/
RUN cd frontend && npm install

COPY frontend ./frontend

WORKDIR /app/frontend

RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
